Add recipe for Spicy Breakfast Potatoes
awoolfe/awoolfe.github.io pull request #1
Opened 2024-05-12 15:15 UTC by IsaacAbramowitz

* Add recipe for `Spicy Breakfast Potatoes`

2024-05-12 17:38 UTC, awoolfe requested changes
Please correct spelling of “potato” singular

2024-05-12 17:59 UTC, IsaacAbramowitz commented
@awoolfe  fixed spelling in commit aabd0293c9c152bfa050ae9aab0de6b45614eaec

2024-05-12 21:27 UTC, awoolfe approved these changes

2024-05-12 21:27 UTC, merged

2024-05-13 13:33 UTC, AnthonyLaye commented on _posts/2024-05-12-spicy-breakfast-potatoes.md
> +Recommended going for a 1:1 potato to other veggie ratio (potato:[pepper & onion]). Feel free to add your own twist to it. I'm not your dad.
I like the flexibility